### ISSUE TITLE
config/vanilladeathchest.toml empty when generated on Fabric server

### ISSUE THREAD

**Issue by pkim168** [TheRandomLabs/VanillaDeathChest#46] opened 2021-01-12 21:10 UTC
Not sure if this is a bug or not, but on my Fabric server, whenever I start the server the contents of the config/vanilladeathchest.toml are set to:
![Capture](https://user-images.githubusercontent.com/25191963/104375014-b75ad680-54f0-11eb-9b56-049c9424d9e5.PNG)

**Comment by TheRandomLabs** [comment] 2021-01-13 00:49
Yep, bug. This is the same as TheRandomLabs/RandomPatches#160.

**Comment by TheRandomLabs** [comment] 2021-01-13 01:09
Oh wait, duplicate of #44.

**Closed as completed by TheRandomLabs** 2021-01-13 01:09 UTC
